# Generated by Django 4.2.4 on 2023-08-14 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_memberfile_table'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivemessage',
            name='receive_member',
        ),
        migrations.AddField(
            model_name='receivemessage',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.member'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('message_title', models.CharField(blank=True, max_length=200)),
                ('message_content', models.CharField(blank=True, max_length=500)),
                ('message_status', models.CharField(choices=[('Y', '읽음'), ('N', '읽지 않음')], default='N', max_length=1)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('receive_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_member', to='member.member')),
            ],
            options={
                'db_table': 'tbl_send_message',
            },
        ),
    ]
