# Generated by Django 4.2.4 on 2023-08-21 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_remove_receivemessage_receive_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='send_message/%Y/%m/%d')),
                ('send_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.sendmessage')),
            ],
            options={
                'db_table': 'tbl_send_message_file',
            },
        ),
        migrations.CreateModel(
            name='ReceiveMessageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='receive_message/%Y/%m/%d')),
                ('receive_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.receivemessage')),
            ],
            options={
                'db_table': 'tbl_receive_message_file',
            },
        ),
    ]
