# Generated by Django 4.2.4 on 2023-08-23 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_sendmessagefile_receivemessagefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessage',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='message.receivemessage'),
        ),
    ]
