# Generated by Django 4.2.4 on 2023-08-16 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_member_latitude_member_member_longitude'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewed_member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_member', to='member.member'),
            preserve_default=False,
        ),
    ]
