# Generated by Django 4.2.4 on 2023-08-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_memberfile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='member_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
