# Generated by Django 4.2.4 on 2023-08-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_location',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
