# Generated by Django 4.2.4 on 2023-08-14 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0002_alter_memberfile_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('pay_status', models.CharField(choices=[('Y', '결제 완료'), ('N', '결제 취소')], default='Y', max_length=1)),
                ('lesson_type', models.CharField(choices=[('Y', '대면'), ('N', '비대면')], default='Y', max_length=1)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='member.member')),
            ],
            options={
                'db_table': 'tbl_payment',
            },
        ),
    ]
