# Generated by Django 4.2.4 on 2023-08-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_language_tag'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='language_tag',
            table='tbl_language_tag',
        ),
    ]
