# Generated by Django 4.2.4 on 2023-08-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_alter_language_tag_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Language_tag',
            new_name='LanguageTag',
        ),
    ]
